// USERS(ADMIN)

export const USER_LIST_FAILER = 'USER_LIST_FAILER';
export const USER_LIST_LOADING = 'USER_LIST_LOADING';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_REST = 'USER_LIST_REST';

export const USER_POST_LOADING = 'USER_POST_LOADING';
export const USER_POST_SUCCESS = 'USER_POST_SUCCESS';
export const USER_POST_FAILER = 'USER_POST_FAILER';
export const USER_POST_REST = 'USER_POST_REST';

export const USER_DELETE_LOADING = ' USER_DELETE_LOADING';
export const USER_DELETE_SUCCESS = ' USER_DELETE_SUCCESS';
export const USER_DELETE_FAILER = 'USER_DELETE_FAILER';
export const USER_DELETE_REST = 'USER_DELETE_REST';

export const USER_UPDATE_LOADING = 'USER_UPDATE_LOADING ';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILER = 'USER_UPDATE_FAILER';
export const USER_UPDATE_REST = 'USER_UPDATE_REST';

export const GET_INDIVIDUAL_USER_LOADING = 'GET_INDIVIDUAL_USER_LOADING';
export const GET_INDIVIDUAL_USER_SUCCESS = 'GET_INDIVIDUAL_USER_SUCCESS';
export const GET_INDIVIDUAL_USER_FAILER = 'GET_INDIVIDUAL_USER_FAILER';
export const GET_INDIVIDUAL_USER_REST = ' GET_INDIVIDUAL_USER_REST';

// AUTH
export const IS_AUTHENTICATED_SUCCESS = 'IS_AUTHENTICATED_SUCCESS';
export const REMOVE_AUTHENTICATED_USER = 'REMOVE_AUTHENTICATED_USER ';

// SIGINUP
export const AUTH_SIGINUP_LOADING = 'AUTH_SIGINUP_LOADING ';
export const AUTH_SIGINUP_SUCCESS = 'AUTH_SIGINUP_SUCCESS';
export const AUTH_SIGINUP_FAILER = 'AUTH_SIGINUP_FAILER';
export const AUTH_SIGINUP_REST = 'AUTH_SIGINUP_REST';

// COMFIRM EMAIL

export const AUTH_CONFIRM_EMAIL_LOADING = 'AUTH_CONFIRM_EMAIL_LOADING';
export const AUTH_CONFIRM_EMAIL_SUCCESS = ' AUTH_CONFIRM_EMAIL_SUCCESS';
export const AUTH_CONFIRM_EMAIL_FAILER = 'AUTH_CONFIRM_EMAIL_FAILER';
export const AUTH_CONFIRM_EMAIL_REST = 'AUTH_CONFIRM_EMAIL_REST';

// LOGIN
export const AUTH_LOGIN_LOADING = 'AUTH_LOGIN_LOADING';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILER = 'AUTH_LOGIN_FAILER';
export const AUTH_LOGIN_REST = 'AUTH_LOGIN_REST';
export const IS_AUTH = 'IS_AUTH';

//FORGET PASSWORD
export const FORGET_PASSWORD_LOADING = 'FORGET_PASSWORD_LOADING';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILER = 'FORGET_PASSWORD_FAILER';
export const FORGET_PASSWORD_REST = 'FORGET_PASSWORD_REST';

// REST PASSWORD
export const REST_PASSWORD_LOADING = 'REST_PASSWORD_LOADING';
export const REST_PASSWORD_SUCCESS = 'REST_PASSWORD_SUCCESS';
export const REST_PASSWORD_FAILER = 'REST_PASSWORD_FAILER';
export const REST_PASSWORD_REST = ' REST_PASSWORD_REST';
