// USERS(ADMIN)

export const USER_LIST_FAILER = 'USER_LIST_FAILER';
export const USER_LIST_LOADING = 'USER_LIST_LOADING';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';

export const USER_POST_LOADING = 'USER_POST_LOADING';
export const USER_POST_SUCCESS = 'USER_POST_SUCCESS';
export const USER_POST_FAILER = 'USER_POST_FAILER';
export const USER_POST_REST = 'USER_POST_REST';

export const USER_DELETE_LOADING = 'USER_DELETE_LOADING';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILER = 'USER_DELETE_FAILER';

export const USER_UPDATE = 'USER_UPDATE';

// LOGIN

export const USER_AUTENICATION_SIGINUP = 'USER_AUTENICATION_SIGNUP';

// AUTH
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILER = 'AUTH_FAILER';

export const AUTH_LOGIN_LOADING = 'AUTH_LOGIN_LOADING';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILER = 'AUTH_LOGIN_FAILER';
export const IS_AUTH = 'IS_AUTH';
