export enum CountriesActionType {
  GET_COUNTRIES_LIST_LOADING = 'GET_COUNTRIES_LIST_LOADING',
  GET_COUNTRIES_LIST_SUCCESS = 'GET_COUNTRIES_LIST_SUCCESS',
  GET_COUNTRIES_LIST_FAILED = 'GET_COUNTRIES_LIST_FAILED',
  GET_COUNTRIES_LIST_REST = 'GET_COUNTRIES_LIST_REST',
}
